### PR TITLE
Update guide

### PR DESCRIPTION
**Pull request by FrancoisPgm**
Updates of the guide:
- GF markdown in local .md files instead of iframe
- Change the slack guide to a Discord guide
- French version

NB : Now GIFs need to be referred with a relative paths, so they must be stored in the repo (I put them in static/img/guide). It should be possible to show GIFs with just an arbitrary URL in theory but for some reason I couldn't get it to work.

### CODE REVIEW

**Comment by FrancoisPgm** [comment]
I didn't notice but the guide is not accessible through the website. I just worked on the markdown files without worrying about the website's structure, but I think we should do something like adding it in the config.yaml.

**Comment by pbellec** [comment]
note: to add it to the website, you need to add the following block
https://github.com/BrainhackMTL/school2020/blob/master/config.yaml#L56-L59

and also in French
https://github.com/BrainhackMTL/school2020/blob/master/config.yaml#L56-L59

You need to adapt the weight parameter because I removed some items in the list.

**Comment by FrancoisPgm** [comment]
I think it's all good now.

**Comment by pbellec** [comment]
LGTM!! thanks a lot.

**Pull request merged**
